INDENT = ' ' * 2
PATH_DELIMITER = '.'
HTML_NB_SPACE = '&nbsp;'
HTML_THIN_SPACE = '&#8239;'
HTML_NEW_LINE = '&#10;'

SHORT_LINE_LEN = 30
MAX_MD_ROW_LEN = 78
JUPYTER_LINE_LEN = 120
DEFAULT_LINE_LEN = MAX_MD_ROW_LEN

DEFAULT_FONT_SIZE = 16
DEFAULT_FONT_PROPORTION = 0.6

REDUNDANT_SPACING = {
    '\n\n': '\n',
}
